ci: change to use GitHub actions
Signed-off-by: PoAn Yang <poan.yang@suse.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,5 +1,16 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM ubuntu:20.04
+
+ARG TARGETPLATFORM
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH ${TARGETPLATFORM#linux/}
+
 COPY GeoLite2-City.mmdb /usr/share/
-COPY upgrade-responder /usr/bin/
+COPY upgrade-responder-${ARCH} /usr/bin/upgrade-responder
 CMD ["upgrade-responder"]
 ENV GEODB /usr/share/GeoLite2-City.mmdb
